### ISSUE TITLE
Rename DemoKafkaSink by  KafkaSink.

### ISSUE THREAD

**Issue by lazaromedina** [keedio/flume-ng-kafka-sink#6]
Due to new convention name the type of agent is 
 agent.sinks.kafka-sink.type = org.keedio.flume.sink.KafkaSink
so must search for KafkaSink instead DemoKafkaSink.

**Comment by lazaromedina** [comment]
Fix bug on developo 0.0.6-SNAPSHOT, new name for sink is KafkaSink.

**Comment by alcuma** [comment]
Hola Luis,

confermo que no esta funcionando:

Si pongo  en la configuracion:
agent-1.sinks.kafka-sink.topic = alessio

me da

25 Jun 2015 09:32:04,661 ERROR [conf-file-poller-0]
(org.apache.flume.node.AbstractConfigurationProvider.loadSinks:432)  - Sink
kafka-sink has been removed due to an error during configuration
org.apache.flume.conf.ConfigurationException: defaultTopic configuration
property not found, it's must be specified.
at org.keedio.flume.sink.KafkaSink.configure(KafkaSink.java:105)
at org.apache.flume.conf.Configurables.configure(Configurables.java:41)
at
org.apache.flume.node.AbstractConfigurationProvider.loadSinks(AbstractConfigurationProvider.java:418)
at
org.apache.flume.node.AbstractConfigurationProvider.getConfiguration(AbstractConfigurationProvider.java:103)
at
org.apache.flume.node.PollingPropertiesFileConfigurationProvider$FileWatcherRunnable.run(PollingPropertiesFileConfigurationProvider.java:140)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)

Si pongo
agent-1.sinks.kafka-sink.defaultTopic = alessio

me da

25 Jun 2015 09:37:23,986 ERROR
[SinkRunner-PollingRunner-DefaultSinkProcessor]
(org.apache.flume.SinkRunner$PollingRunner.run:160)  - Unable to deliver
event. Exception follows.
java.lang.IllegalStateException: close() called when transaction is OPEN -
you must either commit or rollback first
at com.google.common.base.Preconditions.checkState(Preconditions.java:172)
at
org.apache.flume.channel.BasicTransactionSemantics.close(BasicTransactionSemantics.java:179)
at org.keedio.flume.sink.KafkaSink.process(KafkaSink.java:98)
at
org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
at java.lang.Thread.run(Thread.java:744)
25 Jun 2015 09:37:28,989 ERROR
[SinkRunner-PollingRunner-DefaultSinkProcessor]
(org.keedio.flume.sink.KafkaSink.process:89)  - KafkaSink Exception:{}
java.lang.IllegalStateException: begin() called when transaction is OPEN!
at com.google.common.base.Preconditions.checkState(Preconditions.java:145)
at
org.apache.flume.channel.BasicTransactionSemantics.begin(BasicTransactionSemantics.java:131)
at org.keedio.flume.sink.KafkaSink.process(KafkaSink.java:64)
at
org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
at java.lang.Thread.run(Thread.java:744)

...................................................................

Alessio Comisso

*acomisso@keedio.com <acomisso@keedio.com>*|+34 630330033

www.keedio.com

...................................................................


2015-06-24 18:40 GMT+02:00 Luis Lázaro <notifications@github.com>:

**Comment by alcuma** [comment]
# Flume agent config
agent-1.sources = tailFile
agent-1.channels = memoryChannel
agent-1.sinks = kafka-sink

# SOURCES

# tailFile
agent-1.sources.tailFile.type = exec
agent-1.sources.tailFile.command = tail -F
/var/log/ambari-agent/ambari-agent.log
agent-1.sources.tailFile.channels = memoryChannel

# CHANNELS

# memoryChannel
agent-1.channels.memoryChannel.type = memory
#org/apache/flume/sink/kafka/KafkaSink.clas
# SINKS
# fileRoll
agent-1.sinks.kafka-sink.channel = memoryChannel
agent-1.sinks.kafka-sink.type = org.keedio.flume.sink.KafkaSink
agent-1.sinks.kafka-sink.zk.connect = ambari2.ambari.keedio.org:2181
#agent-1.sinks.kafka-sink.topic = alessio
agent-1.sinks.kafka-sink.defaultTopic = alessio
agent-1.sinks.kafka-sink.dynamicTopic = hostname-item
agent-1.sinks.kafka-sink.batch.num.messages = 1000
agent-1.sinks.kafka-sink.queue.buffering.max.ms = 1000
agent-1.sinks.kafka-sink.producer.type = async
agent-1.sinks.kafka-sink.metadata.broker.list =
ambari1.ambari.keedio.org:9092

...................................................................

Alessio Comisso

*acomisso@keedio.com <acomisso@keedio.com>*|+34 630330033

www.keedio.com

...................................................................


2015-06-25 9:40 GMT+02:00 Alessio Comisso <acomisso@keedio.com>:

**Comment by alcuma** [comment]
Hola, l'error me parece lo mismo

25 Jun 2015 12:39:12,082 INFO  [lifecycleSupervisor-1-4]
(org.apache.flume.instrumentation.MonitoredCounterGroup.start:95)  -
Component type: SOURCE, name: tailFile started
25 Jun 2015 12:39:16,088 ERROR
[SinkRunner-PollingRunner-DefaultSinkProcessor]
(org.apache.flume.SinkRunner$PollingRunner.run:160)  - Unable to deliver
event. Exception follows.
java.lang.IllegalStateException: close() called when transaction is OPEN -
you must either commit or rollback first
at com.google.common.base.Preconditions.checkState(Preconditions.java:172)
at
org.apache.flume.channel.BasicTransactionSemantics.close(BasicTransactionSemantics.java:179)
at org.keedio.flume.sink.KafkaSink.process(KafkaSink.java:98)
at
org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
at java.lang.Thread.run(Thread.java:744)
25 Jun 2015 12:39:21,090 ERROR
[SinkRunner-PollingRunner-DefaultSinkProcessor]
(org.keedio.flume.sink.KafkaSink.process:89)  - KafkaSink Exception:{}
java.lang.IllegalStateException: begin() called when transaction is OPEN!
at com.google.common.base.Preconditions.checkState(Preconditions.java:145)
at
org.apache.flume.channel.BasicTransactionSemantics.begin(BasicTransactionSemantics.java:131)
at org.keedio.flume.sink.KafkaSink.process(KafkaSink.java:64)
at
org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
at java.lang.Thread.run(Thread.java:744)

...................................................................

Alessio Comisso

*acomisso@keedio.com <acomisso@keedio.com>*|+34 630330033

www.keedio.com

...................................................................


2015-06-25 11:46 GMT+02:00 Alessio Comisso <acomisso@keedio.com>:
